function make(varargin)
if(size(varargin,2) < 1)
    target = 'all';
else
    target = varargin{1};
end

switch (target)
    case 'all'
        make 2dtria
        make 2dquad
        
    case '2dtria'
        make squad2dtria

    case 'squad2dtria'      
        mex -o squad2dtria        SimpxSimp/squad2dtria.c  ...
            SimpxSimp/squad2dtria_gateway.c  ...
            SimpxSimp/sing_commonedge2dtria.c ...
            SimpxSimp/sing_distant2dtria.c ...
            SimpxSimp/sing_commonvertex2dtria.c ...
            SimpxSimp/sing_identical2dtria.c ...
            SimpxSimp/Ref2PhyS2d_affine.c ...
            SimpxSimp/Ref2PhyS2d_spherical.c ...
            quadpoints.c

    case '2dquad'
        make squad2dquad

    case 'squad2dquad'      
        mex -o squad2dquad         CubexCube/squad2dquad.c  ...
            CubexCube/squad2dquad_gateway.c  ...
            CubexCube/sing_commonedge2dquad.c ...
            CubexCube/sing_commonvertex2dquad.c ...
            CubexCube/sing_identical2dquad.c ...
            CubexCube/Ref2PhyJ2d.c ...
            quadpoints.c
end

end

