#!/bin/bash
for n in {1..10}; do 
  ./cubequad --function=1 --vertexlist=vertexlists/40.dat --n-regular=$n \
             --singular=gauss-jacobi --combination-method=sobol
done > Data/gj-sobol-40
for n in {1..10}; do 
  ./cubequad --function=1 --vertexlist=vertexlists/41.dat --n-regular=$n \
             --singular=gauss-jacobi --combination-method=sobol
done > Data/gj-sobol-41
for n in {1..10}; do 
  ./cubequad --function=1 --vertexlist=vertexlists/42.dat --n-regular=$n \
             --singular=gauss-jacobi --combination-method=sobol
done > Data/gj-sobol-42
for n in {1..10}; do 
  ./cubequad --function=1 --vertexlist=vertexlists/43.dat --n-regular=$n \
             --singular=gauss-jacobi --combination-method=sobol
done > Data/gj-sobol-43
for n in {1..10}; do 
  ./cubequad --function=1 --vertexlist=vertexlists/44.dat --n-regular=$n \
             --singular=gauss-jacobi --combination-method=sobol
done > Data/gj-sobol-44
